image: registry.gitlab.com/mpoehler/firebase-amp-pwa:latest

stages:
  - build-staging
  - deploy-staging

cache:                  
  paths:                
    - node_modules/
    - functions/node_modules/
  key: "$CI_COMMIT_REF_SLUG"

build-staging-functions:
  stage: build-staging
  environment: Staging
  only:
    - master
  script:
    - export STAGING_FIREBASE_TOKEN=$STAGING_FIREBASE_TOKEN
    - npm install -g firebase-tools
    - firebase use $STAGING_FIREBASE_PROJECT --token $STAGING_FIREBASE_TOKEN
    - cd functions
    - npm install
    - npm run build

build-staging-amp-and-app:
  stage: build-staging
  environment: Staging
  only:
    - master
  script:
    - export VERSION=$CI_COMMIT_REF_SLUG
    - export STAGING_FIREBASE_TOKEN=$STAGING_FIREBASE_TOKEN
    - firebase use $STAGING_FIREBASE_PROJECT --token $STAGING_FIREBASE_TOKEN
    - yarn install
    - yarn run build

deploy-staging:
  stage: deploy-staging
  environment: Staging
  only:
    - master
  script:
    - firebase deploy --debug -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $STAGING_FIREBASE_TOKEN --force
