image: registry.gitlab.com/mpoehler/firebase-amp-pwa:latest

stages:
  - build-staging
  - deploy-staging

cache:                  
  paths:                
    - node_modules/
    - functions/node_modules/
  key: "$CI_COMMIT_REF_SLUG"

build-staging-functions:
  stage: build-staging
  environment: Staging
  only:
    - master
  script:
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
    - cd functions
    - npm install
    - npm run build
  artifacts:
    paths:
    - functions/lib

build-staging-amp-and-app:
  stage: build-staging
  environment: Staging
  only:
    - master
  script:
    - export VERSION=$CI_COMMIT_REF_SLUG
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
    - yarn install
    - cd app && yarn install && cd ..
    - yarn run build
  artifacts:
    paths:
    - public

deploy-staging:
  stage: deploy-staging
  environment: Staging
  only:
    - master
  script:
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN --force
