image: node:10.15

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/
    - functions/node_modules/
  key: "$CI_COMMIT_REF_SLUG"

deployproduction:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - npm install -g firebase-tools
    - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
    # build everything
    # build functions
    - cd functions
    - npm install
    - npm run build
    - cd ..
    # build amp pages
    - npm install
    - npm run build
    # build app
    - cd app
    - yarn global add @vue/cli
    - yarn add @vue/cli-service-global
    - yarn build
    - cd ..
    # apply hosting target "website"
    - firebase target:apply hosting website amp-pwa-showcase
    # deploy firebase project
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN --force
